# -*- coding: utf-8 -*-
"""Untitled20.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HlDq68ekITQpZpHV8jQi7LevQ4Ni5MG3
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit

import streamlit as st
import joblib
import numpy as np

st.title("Daiabetes Prediction App")

st.divider()

st.write("With this app you can get prediction for diabetes.")

Age=st.number_input("Enter Age",step=1,min_value=1)
BMI=st.number_input("Enter BMI")
Physactivity=st.number_input("Enter Physical Activity")
SleepTime=st.number_input("Enter Sleep Time")
HvyAlcoholConsump=st.number_input("Enter Heavy Alcohol Consumption")
Smoker=st.number_input("Enter Smoking")

X=[Age,BMI,Physactivity,SleepTime,HvyAlcoholConsump,Smoker]

from sklearn.linear_model import LinearRegression

lr=LinearRegression()

import joblib
joblib.dump(lr,"linearmodel.pkl")
model=joblib.load("linearmodel.pkl")

st.divider()

Predict=st.button("Predict")

if Predict:
  st.balloons()
  X1=np.array([X])
  prediction=model.predict([X1])
  st.write(prediction)